# Clippy configuration file
# https://doc.rust-lang.org/clippy/configuration.html

# Don't complain about unwrap/expect in test code
allow-unwrap-in-tests = true
allow-dbg-in-tests = true
allow-print-in-tests = true

# Recognized identifiers in doc comments
doc-valid-idents = [
    "CDC",
    "CoW",
    "FS",
    "InMemoryConnection",
    "InMemoryListener",
    "MerkleTree",
    "ProtoBuf",
    "QUIC",
    "RiftClient",
    "RiftShareView",
    "TOCTOU",
    "UUID",
    "WalkDir",
]
